### ISSUE TITLE
install_baltrad_common.sh

### ISSUE THREAD

**Issue by agumartina** [openradar/oss_weather_radar_vm#23]
This scrypt is trying to make wget from a googlecode domain, and as we know, that project is closed.
I recommend to change the source from its github project https://github.com/google/keyczar.

`wget https://github.com/google/keyczar/archive/master.zip`
`unzip master.zip`
`cd keyczar-master/python/`
`sudo python setup.py install`

Best regards

Agu

**Comment by DanielMichelson** [comment]
Thank you Agu!
The ORVM only installs and uses the BALTRAD Toolbox packages, not the other
packages used as part of the real-time data exchange and node operation. So
there's actually no need to use the keyczar functionality at all. Since the
VM was developed two years ago, and I have moved to Canada, I have figured
out how to disable keyczar in the Toolbox. So I suggest that this be done
instead of continuing to install keyczar.
best, >-D

**Comment by DanielMichelson** [comment]
This was fixed with PR #26
