### ISSUE TITLE
jupyter does install on top of system python anymore

### ISSUE THREAD

**Issue by heistermann** [openradar/oss_weather_radar_vm#37]
I just tried to build the VM again...it appears that the installation of `jupyter` within the system Python environment fails because `jupyter`'s dependency `tornado` requires a Python version of at least `2.7.9` while the system Python on Trusty is only `2.7.6`. I guess this kind of issue was a long time coming...

It might be possible to downgrade to some previous jupyter version, but I did not find a way, yet. `jupyter` is installed via `provision_scripts/install_scipy_stack.sh`.

Another option might be to migrate to Ubuntu 16.04 (xenial) which provides a more recent system Python (`2.7.11`?). I am just testing that (will keep you updated). However, the actual decision on how to deal with this issue should rather be made by those who use the system Python environment for their course material (wradlib uses conda environments).

Another way would be to fall back to the `ipython notebook`. However, that is not desirable, either, since `jupyter` notebooks are not backward compatible with `ipython` notebooks.

**Comment by heistermann** [comment]
I guess Team BALTRAD (@DanielMichelson) should look into this...I tried to set up the VM with xenial64 (`config.vm.box = ubuntu/xenial64` failed due to [weird user/password settings](https://askubuntu.com/questions/832137/ubuntu-xenial64-box-password)), so I tried `config.vm.box = "bento/ubuntu-16.04"` instead. However, the script `install_baltrad_hlhdf.sh` fails when installing `hlhdf` from source.

**Comment by heistermann** [comment]
`./configure...` works with these changes, but `make test` and `make install` still fail.

**Comment by DanielMichelson** [comment]
Hi,

This is frustrating because Google mail (hosting BALTRAD email) is blocked by my employer so I can only address this on my private phone during the day.

My suggestion is to migrate to Debian 9 Stretch for the course.
Doing so won't solve the problem with HL-HDF because it is caused by Debian (and Ubuntu) changing the name of the HDF5 libraries. This kind of moving target really unnecessary frustrating, but there are solutions as always.

To add to the frustration, I don't have much time for this right now, but it sounds like I have to make time.

Best, daniel

**Comment by heistermann** [comment]
After these changes, `install_baltrad_hlhdf.sh` seems to work. Next in line giving trouble is `install_baltrad_hlhdf.sh`...

**Comment by heistermann** [comment]
@DanielMichelson glad to hear that you'll take a shot - my attempts to heal the BALTRAD installation are pretty clumsy. At least for `install_baltrad_hlhdf.sh`, the changes appeared to be succesful. If you want, you can try my changes so far which are available [here](https://github.com/heistermann/oss_weather_radar_vm/tree/xenialbox). I've still been trying xenial, but I surely do not have any strong preferences here. Let's not forget that the main/original issue was the installation of `jupyter` in an outdated system Python. So if Debian 9 can resolve that - fine! Good luck!

**Comment by DanielMichelson** [comment]
Maik,

I've made some progress this evening with Debian Stretch. I think it will
solve the issue with jupyter.
You figured out the right way of dealing with the HL-HDF build. There are
several additional tweaks required to subsequent BALTRAD provisioning
scripts, since Debian changed the names of system critical directories
(which propagates to Ubuntu). Did I mention how annoyed I am about this?
They have also changed the names of some of the packages installed with
apt-get, which is more understandable.
Anyway, I will need some more time to finish up, including a validation
that the BALTRAD jupyter notebooks work.

The good news is that this gives me a jump on preparations I had planned
for later.

best, >-D

On Tue, Apr 17, 2018 at 11:06 AM, Maik Heistermann <notifications@github.com

**Comment by heistermann** [comment]
Not sure what you mean with "problems related to conda builds". But why not proceed whith a PR and we'll see. I would not expect that switching to Debian should affect conda.

**Comment by DanielMichelson** [comment]
I'm pretty confident this was addressed to everyone's satisfaction last year.
