### ISSUE TITLE
testing of Py-ART's libraries in the VM

### ISSUE THREAD

**Issue by scollis** [openradar/oss_weather_radar_vm#38]
Opening an issue to cover pre-course testing of Py-ART's libraries.

**Comment by scollis** [comment]
Assigning @zssherman to be our lead tester. Zach I will chat with you about this tomorrow.

**Comment by zssherman** [comment]
@scollis Sounds good.

**Comment by heistermann** [comment]
I think one question to answer with regard to Py-ART is whether it should be installed in the same conda environment as wradlib. From the perspective of interoperability, that would be desirable. From the perspective of robustness, each package should have its own environment (in order to avoid last minute surprises with the final VM built). Another option might be to have three conda environments: one for Py-ART (e.g. `pyart_env`), one for wradlib (e.g. `wradlib_env`), and one which tries to include all (which, right now, is called `openradar`). That is a bit redundant, but certainly not the decisive issue with regard to the size of the VM. 

In #35, I had given it a shot to install Py-ART into the `openradar` conda environment (see `provision_scripts/install_pyart.sh`, but something was still faulty, I was not yet able to run the Py-ART stuff successfully. Please be aware that the `openradar` conda environment uses Python 3.6.

If you decide to use `conda` environments for Py-ART, please adhere to the present procedure that uses the `$CONDA_DIR` environment variable to address any conda related stuff (we had to install Miniconda using the `-b` flag in order to avoid conflicts with the system Python). 

Example: 
Instead of 
```
$ source activate $RADARENV
```
you should use

```
source $CONDA_DIR/bin/activate $CONDA_DIR/envs/$RADARENV
```

One more question: Will Py-ART still make use of the system Python environment? If yes, please follow #37 closely and coordinate with @DanielMichelson.

**Comment by zssherman** [comment]
@heistermann When you had issues with the install_pyart script, were it the notebooks that were failing after you got the environment up and running?

I like the idea of an openradar environment, a pyart_env and wradlib_env could be a good backup, but from my experience of having issues with using the system Python at the AMS radar conference tutorial, we turned to conda for users who were having issues. When I saw you implementing conda in the VM I said YAY!! My point being just an openradar environment might be fine, because conda seems to work well, but I'll keep running notebooks and check if there are any issues.

**Comment by zssherman** [comment]
@scollis I assume that for notebooks for ERAD we will turn to cartopy instead of basemap or will we be using both, or just basemap if we stick with some of the old notebooks?

**Comment by scollis** [comment]
Yep.. we want to rip out everything basemap and replace with Cartopy

**Comment by heistermann** [comment]
@zssherman Sorry, I don't remember the exact issue back then, but yes, it was some failure in a notebook. But I really didn't follow up, so if it runs fine now, good!

And if Py-ART and wradlib can live happily together in one conda environment - all the better. We could still add "backup" environments, later, if we want.

**Comment by heistermann** [comment]
Just tried to built the VM with the latest changes. Py-ART does not install sucessfully in the `openradar` conda environment. It fails with a `CondaVerificationError`  which seems to be related to `mkl-2018.0.2-1`.

**Comment by zssherman** [comment]
@heistermann Thanks for the heads up, I will take a look. I'm building the VM now with some changes. I know with 1.9.0 we were having issues with netcdftime, but in pyart 1.9.1 this is fixed. My changes will include the new version of pyart, but the mkl-2018 error is probably something different. I'll try to reproduce the error.

**Comment by zssherman** [comment]
@heistermann I was able to rebuild the environment with my changes and run all the new pyart notebooks found here without error:
https://github.com/EVS-ATMOS/pyart-notebooks

I will submit a pull request with the changes. But I did not encounter the CondaVerificationError.

**Comment by heistermann** [comment]
I built the VM after #48 and everything - BALTRAD, Py-ART, wradlib - seems to run fine. I did not test all notebooks, though, but just samples.
